### ISSUE TITLE
add hru_id_nat to GFV1_catchments_edited

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-network-prep#6]
To make `GFV1_catchments_edited` more useful, we should add the `hru_id_nat` in addition to the `hru_id`

**Comment by lekoenig** [comment]
I agree that it'd be useful to include `hru_id_nat` in the `p2_GFv1_catchments_edited` target. I think the most straightforward approach is to change the GF dataset (`gf_data_select` defined in `_targets.R`) from the regional scheme to the national data.
