### ISSUE TITLE
Check crosswalk table for zero-area COMIDs

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-network-prep#8]
There are PRMS segments where `comid_down`, `comid_seg`, or `comid_cat` are zero-area COMIDs (i.e., with `AREASQKM = 0`). From the drb-inland-salinity-ml, it would be ideal if all COMIDs had attributes. Check these instances of zero-area COMIDs and if possible, omit these from the crosswalk table.

**Comment by jds485** [comment]
Just summarizing some thoughts from Andrew Sekellick on these segments:
These reaches are little extensions, sometimes artificial paths (but sometimes still listed as StreamRiver in NHD)
Sometimes these are flowlines through a waterbody.

We usually don't include these reaches for analysis. It's not really possible to easily tell what is a flowing reach (pretty rare), what is a path through a waterbody, and what is just...a weird NHD thing.
